# Generated by Django 3.2.1 on 2021-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_title'),
        ),
    ]
