# Generated by Django 3.2.1 on 2021-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('title', 'quiz'), name='unique_question_title'),
        ),
    ]
